# Generated by Django 4.1.2 on 2022-10-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, unique=True)),
                ('post_slug', models.SlugField(max_length=350, unique=True)),
                ('author', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='photos/blog/posts/')),
                ('intro', models.TextField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
