# Generated by Django 4.1.2 on 2022-10-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
