# Generated by Django 4.1.2 on 2022-10-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_image_alter_blogpost_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
