# Generated by Django 4.1.2 on 2022-10-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='photos/events')),
                ('is_upcoming', models.BooleanField(default=True)),
                ('link_1_title', models.CharField(blank=True, max_length=100, null=True)),
                ('link_1_url', models.CharField(blank=True, max_length=100, null=True)),
                ('link_2_title', models.CharField(blank=True, max_length=100, null=True)),
                ('link_2_url', models.CharField(blank=True, max_length=100, null=True)),
                ('link_3_title', models.CharField(blank=True, max_length=100, null=True)),
                ('link_3_url', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('Founder', 'Founder'), ('Co-Founder', 'Co-Founder'), ('Core Team', 'Core Team')], default='Core Team', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=300, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
