# Generated by Django 4.1.2 on 2022-10-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=10)),
                ('count', models.IntegerField(default=0)),
                ('pass_image', models.ImageField(upload_to='photos/meetup_pass')),
            ],
        ),
    ]
