# Generated by Django 4.1.2 on 2022-10-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_pass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetuppass',
            name='pass_image',
            field=models.ImageField(blank=True, upload_to='photos/meetup_pass'),
        ),
    ]
