# Generated by Django 4.1.2 on 2022-10-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_pass', '0002_alter_meetuppass_pass_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetuppass',
            name='is_coming',
            field=models.BooleanField(default=True),
        ),
    ]
